#include "uart.h"

void uart_init()
{
	port_out(UART_BASE + UART_FIFO_CONTROL, 
		UART_FCR_RTB_4 | UART_FCR_RST_TRANSMIT | UART_FCR_RST_RECEIVER);
	port_out(UART_BASE + UART_LINE_CONTROL, UART_LCR_DLAB);
	port_out(UART_BASE + UART_DIVISOR_LSB,
	    (UART_FREQ / UART_BAUDRATE) & 0xff);
	port_out(UART_BASE + UART_DIVISOR_MSB,
	    ((UART_FREQ / UART_BAUDRATE) >> 8) & 0xff);
	port_out(UART_BASE + UART_LINE_CONTROL,
	    UART_LCR_DATA_8BIT |
	    UART_LCR_STOP_1BIT |
	    UART_LCR_PARITY_NONE);
}